#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "$BASH_SOURCE[0]")" && cd .. && pwd)"

export DUCKDB_WASM_LOADABLE_EXTENSIONS=1
export DUCKDB_EXTENSION_CONFIGS=extension_config_keepdb_browser.cmake
export DUCKDB_WASM_DUCKDB_EXTENSIONS="${DUCKDB_WASM_DUCKDB_EXTENSIONS:-core_functions}"
export USE_GENERATED_EXPORTED_LIST="${USE_GENERATED_EXPORTED_LIST:-yes}"
export KEEPDB_BROWSER_EXPORT_FILTER="${KEEPDB_BROWSER_EXPORT_FILTER:-1}"

echo "DUCKDB_EXTENSION_CONFIGS=${DUCKDB_EXTENSION_CONFIGS}"
echo "DUCKDB_WASM_DUCKDB_EXTENSIONS=${DUCKDB_WASM_DUCKDB_EXTENSIONS}"
echo "USE_GENERATED_EXPORTED_LIST=${USE_GENERATED_EXPORTED_LIST}"
echo "KEEPDB_BROWSER_EXPORT_FILTER=${KEEPDB_BROWSER_EXPORT_FILTER}"

"${PROJECT_ROOT}/scripts/wasm_build_lib.sh" relsize keepdb-browser "${1:-"${PROJECT_ROOT}/submodules/duckdb"}"
